### ISSUE TITLE
issue to create rule

### ISSUE THREAD

**Issue by jwang628** [pierreforstmann/pg_query_rewrite#2]
i am following https://github.com/pierreforstmann/pg_query_rewrite/

                                            List of installed extensions
        Name        | Version |   Schema   |                              Description                               
--------------------+---------+------------+------------------------------------------------------------------------
 btree_gin          | 1.3     | public     | support for indexing common datatypes in GIN
 pg_buffercache     | 1.3     | public     | examine the shared buffer cache
 pg_query_rewrite   | 0.0.1   | swatPGP1_1 | translate SQL statements

"select pgqr_add_rule('select 10;','select 11;');"
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
connection to server was lost

please advise why an dhow to fix.  thanks

**Comment by pierreforstmann** [comment]
Please check that you have defined in `postgresql.conf` pg_query_rewrite.max_rules with something like:

> pg_query_rewrite.max_rules=10

Looks like that if this parameter is not defined it is set to zero and that extension should be not activated.

if this does not, please give your PostgreSQL version.

**Comment by jwang628** [comment]
any way to check to confirm please?  I added pg_query_rewrite.max_rules=100 in custom.cnf file under etc/conf.d folder

**Comment by jwang628** [comment]
btw, postgresql.conf !include conf.d folder

**Comment by pierreforstmann** [comment]
Restart your instance and check that the setting is valid with:

`show pg_query_rewrite.max_rules;`

If the setting is valid, try:

`select pgqr_add_rule('select 10;','select 11;');`

**Comment by jwang628** [comment]
found out why:  can not make it 100 - changed to 10 and 

select pgqr_add_rule('select 10;','select 11;');  #worked
"select pgqr_add_rule('select 10;','select 11;');"
 pgqr_add_rule 
---------------
 t
(1 row)
[db169156.phx201

however, select 10; shows 10 not 11 :(

thanks for your help so far.

**Comment by pierreforstmann** [comment]
If this does not work please try to give a reproducible test case with the exact PostgreSQL version that is used.

**Comment by jwang628** [comment]
"SELECT version()"
                                          version                                           
--------------------------------------------------------------------------------------------
 PostgreSQL 14.4 (Release) on x86_64-pc-linux-gnu, compiled by clang version 13.0.0, 64-bit
(1 row)

**Comment by pierreforstmann** [comment]
I cannot reproduce this issue.

I use [pgenv](https://github.com/theory/pgenv) to create a PG 14.4 instance on AlmaLinux release 8.7 (Stone Smilodon).

I installed extensions, added to  `postgresql.conf`
```
shared_preload_libraries = 'pg_query_rewrite'	# (change requires restart)
pg_query_rewrite.max_rules=10
```
and restarted PG instance.

And I run as superuser:
```
select version();
                                                 version                                                 
---------------------------------------------------------------------------------------------------------
 PostgreSQL 14.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10), 64-bit
(1 row)

select * from pg_extension;
  oid  |     extname      | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+------------------+----------+--------------+----------------+------------+-----------+--------------
 13011 | plpgsql          |       10 |           11 | f              | 1.0        |           | 
 16828 | pg_query_rewrite |    16826 |         2200 | f              | 0.0.1      |           | 
 16833 | btree_gin        |    16826 |         2200 | t              | 1.3        |           | 
 17269 | pg_buffercache   |    16826 |         2200 | t              | 1.3        |           | 
(4 rows)

show  pg_query_rewrite.max_rules;
 pg_query_rewrite.max_rules 
----------------------------
 10
(1 row)

select pgqr_add_rule('select 10;','select 11;');
 pgqr_add_rule 
---------------
 t
(1 row)

select 10;
 ?column? 
----------
       11
(1 row)
```
